// Copyright (C) 2016 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
// Qt-Security score:significant reason:default

#include "sbkmodule.h"
#include "autodecref.h"
#include "basewrapper.h"
#include "bindingmanager.h"
#include "sbkstring.h"
#include "sbkcppstring.h"
#include "sbkconverter_p.h"
#include "sbkcoarsebindinglock.h"
#include "sbkpep.h"
#ifdef Py_GIL_DISABLED
#  include "sbkftoptions.h"
#endif

#include <algorithm>
#include <array>
#include <mutex>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <cstdlib>
#include <cstring>
#include <string_view>

/// This hash maps module objects to arrays of converters.
using ModuleConvertersMap = std::unordered_map<PyObject *, SbkConverter **> ;

/// This hash maps module objects to arrays of Python types.
using ModuleTypesMap = std::unordered_map<PyObject *, Shiboken::Module::TypeInitStruct *> ;

struct TypeCreationStruct
{
    Shiboken::Module::TypeCreationFunction func{nullptr};
    std::vector<std::string> subtypeNames;
};

/// This hash maps type names to type creation structs.
using NameToTypeFunctionMap = std::unordered_map<std::string, TypeCreationStruct> ;

/// This hash maps module objects to maps of names to functions.
using ModuleToFuncsMap = std::unordered_map<PyObject *, NameToTypeFunctionMap> ;

/// All types produced in imported modules are mapped here.
struct ModuleGlobalData
{
    ModuleTypesMap moduleTypes;
    ModuleConvertersMap moduleConverters;
};

static ModuleGlobalData *moduleGlobalData()
{
    static ModuleGlobalData globals;
    return &globals;
}

// Data that would exist per interpreter if subinterpreter support was
// implemented.
struct ModuleData
{
    ModuleToFuncsMap moduleToFuncs;

    // PYSIDE-2404: These modules produce ambiguous names which we cannot handle, yet.
    std::unordered_set<std::string> dontLazyLoad;

    // PYSIDE-2404: Redirecting import for "import *" support.
    //
    // The first import will be handled by the isImportStar function. But the
    // same module might be imported twice, which would give no introspection
    // due to module caching.
    PyObject *origImportFunc{};

    PyObject *sysModules{PyImport_GetModuleDict()};
    PyObject *partial{Pep_GetPartialFunction()};
    bool lazy_init = false;
};

static ModuleData *moduleData()
{
    static ModuleData data;
    return &data;
}

// PYSIDE-2404: Lazy type creation is a one-time initialization and must run
// exactly once, but nothing enforced that. A name stays in nameToFunc while
// its creation function runs, so on a free-threaded build a second thread
// entering that window calls the same creation function again - two threads
// building one type, plus concurrent find()/erase() on the same unordered_map.
// Observed as a crash in QtQml_qqmlnetwork_test: Qt's QML loader thread
// converts a QObject to Python (which incarnates QSGTexture) while the main
// thread incarnates QQuickRhiItem.
//
// Serialize the whole lazy path. Two properties make this safe rather than a
// new deadlock source:
//
// - The lock is recursive, because creation nests on one thread: incarnating
//   QSGDynamicTexture incarnates QSGTexture, and creating the enums calls back
//   into Python.
// - A thread that has to wait detaches first. It therefore holds nothing while
//   it waits - in particular the object graph guard is suspended and its mutex
//   released - so it cannot take part in a cycle, and it does not stall a
//   stop-the-world pause.
#ifdef Py_GIL_DISABLED

static std::recursive_mutex &lazyInitMutex()
{
    static std::recursive_mutex mutex;
    return mutex;
}

static bool lazyInitLockEnabled()
{
    return Shiboken::FreeThreading::optionEnabled(
        Shiboken::FreeThreading::LazyTypeLock);
}

class LazyInitLock
{
public:
    LazyInitLock(const LazyInitLock &) = delete;
    LazyInitLock &operator=(const LazyInitLock &) = delete;
    LazyInitLock(LazyInitLock &&) = delete;
    LazyInitLock &operator=(LazyInitLock &&) = delete;

    LazyInitLock() : m_active(lazyInitLockEnabled())
    {
        // Uncontended, and re-entry from the owning thread, take no detour.
        if (m_active && !lazyInitMutex().try_lock()) {
            Py_BEGIN_ALLOW_THREADS
            lazyInitMutex().lock();
            Py_END_ALLOW_THREADS
        }
    }
    ~LazyInitLock()
    {
        if (m_active)
            lazyInitMutex().unlock();
    }

private:
    bool m_active;
};

#endif // Py_GIL_DISABLED

namespace Shiboken::Module
{

// PYSIDE-2404: Replacing the arguments generated by cpythonTypeNameExt
//              by a function call.
LIBSHIBOKEN_API PyTypeObject *get(TypeInitStruct &typeStruct)
{
    if (typeStruct.type != nullptr)
        return typeStruct.type;

    // The slow path for initialization.
    // We get the type by following the chain from the module.
    // As soon as types[index] gets filled, we can stop.

#ifdef Py_GIL_DISABLED
    LazyInitLock lock;
    // Another thread may have finished the type while we waited for the lock.
    if (typeStruct.type != nullptr)
        return typeStruct.type;
#endif

    std::string_view names(typeStruct.fullName);
    const bool usePySide = names.compare(0, 8, "PySide6.") == 0;
    auto dotPos = usePySide ? names.find('.', 8) : names.find('.');
    auto startPos = dotPos + 1;
    AutoDecRef modName(String::fromCppStringView(names.substr(0, dotPos)));
    auto *modOrType = PyDict_GetItem(moduleData()->sysModules, modName);
    if (modOrType == nullptr) {
        PyErr_Format(PyExc_SystemError,
                     R"(libshiboken: Error instantiating "%s": Module "%U" should already be in sys.modules)",
                     typeStruct.fullName, modName.object());
        return nullptr;
    }

    do {
        dotPos = names.find('.', startPos);
        auto typeName = dotPos != std::string::npos
                        ? names.substr(startPos, dotPos - startPos)
                        : names.substr(startPos);
        startPos = dotPos + 1;
        AutoDecRef obTypeName(String::fromCppStringView(typeName));
        modOrType = PyObject_GetAttr(modOrType, obTypeName);
    } while (typeStruct.type == nullptr && dotPos != std::string::npos);

    return typeStruct.type;
}

// For a subtype like "Namespace.OuterClass.InnerClass" find the "OuterClass"
// type by walking the dictionaries from the module looking up the attributes.
// For main types, it will return the module passed in.
static PyObject *getEnclosingObject(PyObject *modOrType, std::string_view namePath)
{
    auto dotPos = namePath.find('.');
    std::string::size_type startPos = 0;
    while (dotPos != std::string::npos) {
        auto typeName = namePath.substr(startPos, dotPos - startPos);
        AutoDecRef obTypeName(String::fromCppStringView(typeName));
        auto *next = PyObject_GetAttr(modOrType, obTypeName.object());
        assert(next);
        modOrType = next;
        startPos = dotPos + 1;
        dotPos = namePath.find('.', startPos);
    }
    return modOrType;
}

static void incarnateHelper(PyObject *enclosing, std::string_view names,
                            const TypeCreationStruct &tcStruct)
{
    PyTypeObject *type = tcStruct.func(enclosing);
    assert(type != nullptr);
    auto *obType = reinterpret_cast<PyObject *>(type);
    if (PyModule_Check(enclosing) != 0) {
        Py_INCREF(obType);
        PepModule_AddType(enclosing, type); // steals reference
    } else {
        const auto dotPos = names.rfind('.');
        const std::string_view name = dotPos != std::string::npos ? names.substr(dotPos + 1) : names;
        AutoDecRef nameP(String::fromCppStringView(name));
        PyObject_SetAttr(enclosing, nameP, obType);
    }
}

// Called by shouldLoadImmediately()
static void incarnateHelper(PyObject *module, std::string_view names,
                            const NameToTypeFunctionMap &nameToFunc)
{
    // now we have the type to create. (May be done already)
    auto funcIter = nameToFunc.find(std::string(names));
    if (funcIter != nameToFunc.end())
        incarnateHelper(getEnclosingObject(module, names), names, funcIter->second);
}

static void incarnateSubtypes(PyObject *obMainType,
                              const std::vector<std::string> &nameList,
                              NameToTypeFunctionMap &nameToFunc)
{
    for (const auto &name : nameList) {
        auto funcIter = nameToFunc.find(name);
        if (funcIter != nameToFunc.end()) {
            // We skip the look up of the main type from the module,
            // passing the the main type as enclosing type.
            const auto dotPos = name.find('.');
            assert(dotPos != std::string::npos);
            auto subTypeName = std::string_view{name}.substr(dotPos + 1);
            auto *enclosing = getEnclosingObject(obMainType, subTypeName);
            incarnateHelper(enclosing, subTypeName, funcIter->second);
            nameToFunc.erase(funcIter);
        }
    }
}

static PyTypeObject *incarnateType(PyObject *module, const std::string &name,
                                   NameToTypeFunctionMap &nameToFunc)
{
    // - locate the name and retrieve the generating function
    auto funcIter = nameToFunc.find(name);
    if (funcIter == nameToFunc.end()) {
        // attribute does really not exist.
        PyErr_SetNone(PyExc_AttributeError);
        return nullptr;
    }
    // - call this function that returns a PyTypeObject
    auto tcStruct = funcIter->second;
    auto initFunc = tcStruct.func;
    auto *modOrType{module};

    // PYSIDE-2404: Make sure that no switching happens during type creation.
    auto saveFeature = initSelectableFeature(nullptr);
    PyTypeObject *type = initFunc(modOrType);

    // - assign this object to the name in the module (for adding subtypes)
    auto *obType = reinterpret_cast<PyObject *>(type);
    Py_INCREF(obType);
    PepModule_AddType(module, type);   // steals reference

    if (!tcStruct.subtypeNames.empty())
        incarnateSubtypes(obType, tcStruct.subtypeNames, nameToFunc);
    initSelectableFeature(saveFeature);

    // - remove the entry, if not by something cleared.
    if (!nameToFunc.empty())
        nameToFunc.erase(funcIter);
    // - return the PyTypeObject.
    return type;
}

// PYSIDE-2404: Make sure that the mentioned classes really exist.
// Used in `Pyside::typeName`. Because the result will be cached by
// the creation of the type(s), this is efficient.
void loadLazyClassesWithNameStd(const std::string &name)
{
#ifdef Py_GIL_DISABLED
    LazyInitLock lock;
#endif
    for (auto const & tableIter : moduleData()->moduleToFuncs) {
        auto nameToFunc = tableIter.second;
        auto funcIter = nameToFunc.find(name);
        if (funcIter != nameToFunc.end()) {
            // attribute exists in the lazy types.
            auto *module = tableIter.first;
            incarnateType(module, name, nameToFunc);
        }
    }
}

void loadLazyClassesWithName(const char *name)
{
    loadLazyClassesWithNameStd(std::string(name));
}

// PYSIDE-2404: Completely load all not yet loaded classes.
//              This is needed to resolve a star import.
// PYSIDE-2898: Use a name list to pick the toplevel types.
void resolveLazyClasses(PyObject *module)
{
#ifdef Py_GIL_DISABLED
    LazyInitLock lock;
#endif
    // - locate the module in the moduleTofuncs mapping
    auto &moduleToFuncs = moduleData()->moduleToFuncs;
    auto tableIter = moduleToFuncs.find(module);
    if (tableIter == moduleToFuncs.end())
        return;

    // - see if there are still unloaded elements
    auto &nameToFunc = tableIter->second;

    // - keep a filtered list of names without the subtypes
    std::vector<std::string> names{};
    names.reserve(nameToFunc.size());
    for (const auto &funcIter : nameToFunc) {
        if (funcIter.first.find('.') == std::string::npos)
            names.push_back(funcIter.first);
    }

    // - incarnate all toplevel types. Subtypes are handled there.
    for (const auto &nameIter : names) {
        auto funcIter = nameToFunc.find(nameIter);
        if (funcIter != nameToFunc.end())
            incarnateType(module, nameIter, nameToFunc);
    }
}

// PYSIDE-2404: Override the gettattr function of modules.
static getattrofunc origModuleGetattro{};

// PYSIDE-2404: Use the patched module getattr to do on-demand initialization.
//              This modifies _all_ modules but should have no impact.
static PyObject *PyModule_lazyGetAttro(PyObject *module, PyObject *name)
{
    // - check if the attribute is present and return it.
    auto *attr = PyObject_GenericGetAttr(module, name);
    // - we handle AttributeError, only.
    if (attr != nullptr || PyErr_ExceptionMatches(PyExc_AttributeError) == 0)
        return attr;

    PyErr_Clear();
    // Only the lazy path is serialized; the hit above is the common case and
    // this function is installed for every module in the process.
#ifdef Py_GIL_DISABLED
    LazyInitLock lock;
#endif
    // - locate the module in the moduleTofuncs mapping
    auto &moduleToFuncs = moduleData()->moduleToFuncs;
    auto tableIter = moduleToFuncs.find(module);
    // - if this is not our module, use the original
    if (tableIter == moduleToFuncs.end())
        return origModuleGetattro(module, name);

    // - locate the name and retrieve the generating function
    const char *attrNameStr = Shiboken::String::toCString(name);
    auto &nameToFunc = tableIter->second;
    // - create the real type and handle subtypes
    auto *type = incarnateType(module, attrNameStr, nameToFunc);
    auto *ret = reinterpret_cast<PyObject *>(type);
    // - if attribute does really not exist use the original
    if (ret == nullptr && PyErr_ExceptionMatches(PyExc_AttributeError)) {
        PyErr_Clear();
        return origModuleGetattro(module, name);
    }
    return ret;
}

// PYSIDE-2404: Supply a new module dir for not yet visible entries.
//              This modification is only for "our" modules.
static PyObject *_module_dir_template(PyObject * /* self */, PyObject *args)
{
    static PyObject *const _dict = Shiboken::String::createStaticString("__dict__");
    // The dir function must replace all of the builtin function.
    PyObject *module{};
    if (!PyArg_ParseTuple(args, "O", &module))
        return nullptr;

    auto &moduleToFuncs = moduleData()->moduleToFuncs;
    auto tableIter = moduleToFuncs.find(module);
    assert(tableIter != moduleToFuncs.end());
    Shiboken::AutoDecRef dict(PyObject_GetAttr(module, _dict));
    auto *ret = PyDict_Keys(dict);
    // Now add all elements that were not yet in the dict.
    auto &nameToFunc = tableIter->second;
    for (const auto &funcIter : nameToFunc) {
        if (funcIter.first.find('.') == std::string::npos) { // no nested types
            Shiboken::AutoDecRef pyName(Shiboken::String::fromCppString(funcIter.first));
            PyList_Append(ret, pyName);
        }
    }
    return ret;
}

static PyMethodDef module_methods[] = {
    {"__dir__", _module_dir_template, METH_VARARGS, nullptr},
    {nullptr, nullptr, 0, nullptr}
};

// OpCodes: Adapt for each Python version by checking the defines in the generated header opcode_ids.h
// egrep '( LOAD_CONST | IMPORT_NAME )' opcode_ids.h
// See also sbkfeature_base.cpp:115

static int constexpr LOAD_CONST_OpCode(long pyVersion)
{
    if (pyVersion >= 0x030F00) // 3.15
        return 81;
    if (pyVersion >= 0x030E00) // 3.14
        return 82;
    if (pyVersion >= 0x030D00) // 3.13
        return 83;
    return 100;
}

static int constexpr IMPORT_NAME_OpCode(long pyVersion)
{
    if (pyVersion >= 0x030F00) // 3.15
        return 72;
    if (pyVersion >= 0x030E00) // 3.14
        return 73;
    if (pyVersion >= 0x030D00) // 3.13
        return 75;
    return 108;
}

static bool detectImportStar(PyObject *dec_frame, PyObject *module)
{
    static PyObject *const _f_code = Shiboken::String::createStaticString("f_code");
    static PyObject *const _f_lasti = Shiboken::String::createStaticString("f_lasti");
    static PyObject *const _co_code = Shiboken::String::createStaticString("co_code");
    static PyObject *const _co_consts = Shiboken::String::createStaticString("co_consts");
    static PyObject *const _co_names = Shiboken::String::createStaticString("co_names");

    static const long pyVersion = _PepRuntimeVersion();
    static const int LOAD_CONST = LOAD_CONST_OpCode(pyVersion);
    static const int IMPORT_NAME = IMPORT_NAME_OpCode(pyVersion);

    AutoDecRef dec_f_code(PyObject_GetAttr(dec_frame, _f_code));
    AutoDecRef dec_co_code(PyObject_GetAttr(dec_f_code, _co_code));
    AutoDecRef dec_f_lasti(PyObject_GetAttr(dec_frame, _f_lasti));
    if (dec_f_code.isNull() || dec_co_code.isNull() || dec_f_lasti.isNull())
        return false;

    Py_ssize_t code_len{};
    char *co_code{};
    if (PyBytes_AsStringAndSize(dec_co_code, &co_code, &code_len) != 0)
        return false;

    const Py_ssize_t f_lasti = PyLong_AsSsize_t(dec_f_lasti);
    if (f_lasti < 2 || f_lasti >= code_len - 1
        || co_code[f_lasti] != IMPORT_NAME || co_code[f_lasti - 2] != LOAD_CONST) {
        return false;
    }

    const Py_ssize_t oparg1 = uint8_t(co_code[f_lasti - 1]);
    AutoDecRef dec_co_consts(PyObject_GetAttr(dec_f_code, _co_consts));
    if (dec_co_consts.isNull() || PyTuple_Check(dec_co_consts.object()) == 0
        || oparg1 >= PyTuple_Size(dec_co_consts.object())) {
        return false;
    }

    auto *fromlist = PyTuple_GetItem(dec_co_consts, oparg1);
    if (PyTuple_Check(fromlist) == 0 || PyTuple_Size(fromlist) != 1
        || Shiboken::String::toCString(PyTuple_GetItem(fromlist, 0))[0] != '*') {
        return false;
    }

    Py_ssize_t oparg2 = uint8_t(co_code[f_lasti + 1]);
    // Cf cpython/46d5106cfa903329821c097c3bf309e3efcd718f, Lazy import in 3.15,
    //cpython/Python/generated_cases.c.h:6410
    if (pyVersion >= 0x030F00) // 3.15
        oparg2 >>= 2;
    AutoDecRef dec_co_names(PyObject_GetAttr(dec_f_code, _co_names));
    if (dec_co_names.isNull() || PyTuple_Check(dec_co_names.object()) == 0
        || oparg2 >= PyTuple_Size(dec_co_names.object())) {
        return false;
    }
    const char *name = String::toCString(PyTuple_GetItem(dec_co_names, oparg2));
    const char *modName = PyModule_GetName(module);
    return std::strcmp(name, modName) == 0;
}

static bool isImportStar(PyObject *module)
{
    // Find out whether we have a star import. This must work even
    // when we have no import support from feature.

    static PyObject *const _f_back = Shiboken::String::createStaticString("f_back");

    auto *obFrame = reinterpret_cast<PyObject *>(PyEval_GetFrame());
    if (obFrame == nullptr)
        return true;            // better assume worst-case.

    Py_INCREF(obFrame);
    AutoDecRef dec_frame(obFrame);

    // Calculate the offset of the running import_name opcode on the stack.
    // Right before that there must be a load_const with the tuple `("*",)`.
    while (dec_frame.object() != Py_None) {
        if (detectImportStar(dec_frame.object(), module))
            return true;
        dec_frame.reset(PyObject_GetAttr(dec_frame, _f_back));
    }
    return false;
}

static constexpr std::array<std::string_view, 7> knownModules {
    "shiboken6.Shiboken",
    "minimal",
    "other",
    "sample",
    "smart",
    "scriptableapplication",
    "testbinding"
};

static bool canNotLazyLoad(const std::string &modName)
{
    // There are no more things that must be disabled :-D
    const auto &dontLazyLoad = moduleData()->dontLazyLoad;
    return dontLazyLoad.find(modName) != dontLazyLoad.end();
}

static bool shouldLazyLoad(const std::string &modName)
{
    if (std::find(knownModules.cbegin(), knownModules.cend(), modName) != knownModules.cend())
        return true;

    return modName.compare(0, 8, "PySide6.") == 0;
}

static int lazyLoadDefault()
{
#ifndef PYPY_VERSION
    int result = 1;
#else
    int result = 0;
#endif
    if (auto *flag = getenv("PYSIDE6_OPTION_LAZY"))
        result = std::atoi(flag);
    return result;
}

static bool shouldLoadImmediately(PyObject *module)
{
    static const int value = lazyLoadDefault();

    // PYSIDE-2404: Lazy Loading
    //
    // Options:
    //   0  - switch lazy loading off.
    //   1  - lazy loading for all known modules.
    //   3  - lazy loading for any module.
    //
    // By default we lazy load all known modules (option = 1).
    if (value == 0)
        return true; // completely disabled
    const std::string modName(PyModule_GetName(module));
    if (canNotLazyLoad(modName))
        return true; // for some reason we cannot lazy load (star import of module)
    return value == 1 && !shouldLazyLoad(modName);
}

void AddTypeCreationFunction(PyObject *module,
                             const char *name,
                             TypeCreationFunction func)
{
#ifdef Py_GIL_DISABLED
    LazyInitLock lock;
#endif
    // - locate the module in the moduleTofuncs mapping
    auto &moduleToFuncs = moduleData()->moduleToFuncs;
    auto tableIter = moduleToFuncs.find(module);
    assert(tableIter != moduleToFuncs.end());
    // - Assign the name/generating function tcStruct.
    auto &nameToFunc = tableIter->second;
    TypeCreationStruct tcStruct{func, {}};
    auto nit = nameToFunc.find(name);
    if (nit == nameToFunc.end())
        nameToFunc.insert(std::make_pair(name, tcStruct));
    else
        nit->second = tcStruct;

    if (shouldLoadImmediately(module))
        incarnateHelper(module, name, nameToFunc);
}

void AddTypeCreationFunction(PyObject *module,
                             const char *enclosingName,
                             TypeCreationFunction func,
                             const char *subTypeNamePath)
{
#ifdef Py_GIL_DISABLED
    LazyInitLock lock;
#endif
    // - locate the module in the moduleTofuncs mapping
    auto &moduleToFuncs = moduleData()->moduleToFuncs;
    auto tableIter = moduleToFuncs.find(module);
    assert(tableIter != moduleToFuncs.end());
    // - Assign the name/generating function tcStruct.
    auto &nameToFunc = tableIter->second;
    auto nit = nameToFunc.find(enclosingName);

    // - insert namePath into the subtype vector of the main type.
    std::string namePath(subTypeNamePath);
    nit->second.subtypeNames.emplace_back(namePath);
    // - insert it also as its own entry.
    nit = nameToFunc.find(namePath);
    TypeCreationStruct tcStruct{func, {}};
    if (nit == nameToFunc.end())
        nameToFunc.insert(std::make_pair(namePath, tcStruct));
    else
        nit->second = tcStruct;

    if (shouldLoadImmediately(module))
        incarnateHelper(module, namePath, nameToFunc);
}

PyObject *import(const char *moduleName)
{
    PyObject *sysModules = PyImport_GetModuleDict();
    PyObject *module = PyDict_GetItemString(sysModules, moduleName);
    if (module != nullptr)
        Py_INCREF(module);
    else
        module = PyImport_ImportModule(moduleName);

    if (module == nullptr) {
        PyErr_Format(PyExc_ImportError,
                     "libshiboken: could not import module '%s'", moduleName);
    }

    return module;
}

static PyObject *lazy_import(PyObject * /* self */, PyObject *args, PyObject *kwds)
{
    auto *ret = PyObject_Call(moduleData()->origImportFunc, args, kwds);
    if (ret != nullptr) {
        // PYSIDE-2404: Support star import when lazy loading.
        if (PyTuple_Size(args) >= 4) {
            auto *fromlist = PyTuple_GetItem(args, 3);
            if (PyTuple_Check(fromlist) && PyTuple_Size(fromlist) == 1
                    && Shiboken::String::toCString(PyTuple_GetItem(fromlist, 0))[0] == '*')
                Shiboken::Module::resolveLazyClasses(ret);
        }
    }
    return ret;
}

#ifdef __clang__
#  pragma clang diagnostic push
#  pragma clang diagnostic ignored "-Wcast-function-type-mismatch"
#endif
static PyMethodDef lazy_methods[] = {
    {"__lazy_import__", reinterpret_cast<PyCFunction>(lazy_import), METH_VARARGS | METH_KEYWORDS, nullptr},
    {nullptr, nullptr, 0, nullptr}
};
#ifdef __clang__
#  pragma clang diagnostic pop
#endif

PyObject *createOnly(const char * /* moduleName */, PyModuleDef *moduleData)

{
    Shiboken::init();
    auto *module = PyModule_Create(moduleData);
    if (module == nullptr) {
        PyErr_Print();
        return nullptr;
    }
    return module;
}

PyObject *create(const char *moduleName, PyModuleDef *moduleData)
{
    auto *module = createOnly(moduleName, moduleData);
    if (module != nullptr)
        exec(module);
    return module;
}

void exec(PyObject *module)
{
#ifdef Py_GIL_DISABLED
    // The module declares that it does not need the GIL, which only holds
    // while the coarse binding lock is in place. Clearing its PYSIDE6_OPTION_FT bit takes that
    // lock away, leaving the bindings free-threaded with no synchronization
    // at all. Taking the declaration back here is not possible - the GIL slot
    // is evaluated when the module is created, before this runs - so say so
    // instead. The switch exists for the stress harness, not for production.
    static bool warned = false;
    if (!coarseBindingLockEnabled() && !warned) {
        warned = true;
        PyErr_WarnEx(PyExc_RuntimeWarning,
                     "Clearing the CoarseBindingLock bit of PYSIDE6_OPTION_FT "
                     "disables the lock that makes the bindings safe without "
                     "the GIL. This is meant for stress testing only; data "
                     "races are expected.", 1);
        PyErr_Clear(); // a warning turned into an error must not fail the import
    }
#endif
    auto *data = moduleData();
    // Setup of a dir function for "missing" classes.
    auto *moduleDirTemplate = PyCFunction_NewEx(module_methods, nullptr, nullptr);
    // Turn this function into a bound object, so we have access to the module.
    auto *moduleDir = PyObject_CallFunctionObjArgs(data->partial, moduleDirTemplate, module, nullptr);
    PepModule_Add(module, module_methods->ml_name, moduleDir);  // steals reference
    // Insert an initial empty table for the module.
    NameToTypeFunctionMap empty;
    data->moduleToFuncs.insert(std::make_pair(module, empty));

    // A star import must be done unconditionally. Use the complete name.
    if (isImportStar(module))
        data->dontLazyLoad.insert(PyModule_GetName(module));

    if (!data->lazy_init) {
        // Install the getattr patch.
        origModuleGetattro = PyModule_Type.tp_getattro;
        PyModule_Type.tp_getattro = PyModule_lazyGetAttro;
        // Add the lazy import redirection, keeping a reference.
        Shiboken::AutoDecRef builtins(PepEval_GetFrameBuiltins());
        data->origImportFunc = PyDict_GetItemString(builtins.object(), "__import__");
        Py_INCREF(data->origImportFunc);
        AutoDecRef func(PyCFunction_NewEx(lazy_methods, nullptr, nullptr));
        PyDict_SetItemString(builtins.object(), "__import__", func);
        data->lazy_init = true;
    }
    // PYSIDE-2404: Nuitka inserts some additional code in standalone mode
    //              in an invisible virtual module (i.e. `QtCore-postLoad`)
    //              that gets imported before the running import can call
    //              `_PyImport_FixupExtensionObject` which does the insertion
    //              into `sys.modules`. This can cause a race condition.
    // Insert the module early into the module dict to prevent recursion.
    PyDict_SetItemString(data->sysModules, PyModule_GetName(module), module);
    // Clear the non-existing name cache because we have a new module.
    Shiboken::Conversions::clearNegativeLazyCache();
}

void registerTypes(PyObject *module, TypeInitStruct *types)
{
    auto &moduleTypes = moduleGlobalData()->moduleTypes;
    auto iter = moduleTypes.find(module);
    if (iter == moduleTypes.end())
        moduleTypes.insert(std::make_pair(module, types));
}

TypeInitStruct *getTypes(PyObject *module)
{
    auto &moduleTypes = moduleGlobalData()->moduleTypes;
    auto iter = moduleTypes.find(module);
    return (iter == moduleTypes.end()) ? 0 : iter->second;
}

void registerTypeConverters(PyObject *module, SbkConverter **converters)
{
    auto &moduleConverters = moduleGlobalData()->moduleConverters;
    auto iter = moduleConverters.find(module);
    if (iter == moduleConverters.end())
        moduleConverters.insert(std::make_pair(module, converters));
}

SbkConverter **getTypeConverters(PyObject *module)
{
    auto &moduleConverters = moduleGlobalData()->moduleConverters;
    auto iter = moduleConverters.find(module);
    return (iter == moduleConverters.end()) ? 0 : iter->second;
}

// Replace the dictionary of a module by a different dict.
// The dict should be filled with the content of the old dict, before.
// Reason: Creating a module dict with __missing__ support.
struct StartOf_PyModuleObject {
    PyObject_HEAD
    PyObject *md_dict;
};

bool replaceModuleDict(PyObject *module, PyObject *modClass, PyObject *dict)
{
    if (!(PyModule_Check(module) && PyType_Check(modClass) && PyDict_Check(dict)))
        return false;
    auto *modict = PyModule_GetDict(module);
    auto *modIntern = reinterpret_cast<StartOf_PyModuleObject *>(module);
    if (modict != modIntern->md_dict)
        Py_FatalError("libshiboken: The layout of modules is incompatible");
    auto *hold = modIntern->md_dict;
    modIntern->md_dict = dict;
    Py_INCREF(dict);
    Py_DECREF(hold);
    Py_INCREF(modClass);
    module->ob_type = reinterpret_cast<PyTypeObject *>(modClass);
    return true;
}

} // namespace Shiboken::Module
